### ISSUE TITLE
Dinosaur Cards - created from dinosaur array

### ISSUE THREAD

**Issue by terrifricker** [chingu-voyages/v48-tier1-team-05#53]
**__Task Description__**
Using the dinosaur array or the filtered array as function parameters, write a javascript function that will create a new DOM element for each item in the array.  Use DOM manipulation to place the new cards into the card container described in index.html.

David has created a format and styling for the dinosaur cards, using the following html elements:
`.card-container` for the outside container of the back of the dinosaur card showing the dinosaur details
`.card-container-1` for the outer container of the text portion of the card
`.card-container-2` for the image portion of the card
`dl` the description list html element for the text portion of the card
`dt` the description term html element for each key of the dinosaur object we want to display
`dd` the description details html element for the value corresponding to the key in the dinosaur object
`span` the span html element around each \<dt> element for styling the terms.

If desired, you can simplify the html as needed to reduce the number of html elements to be created, for example removing the card-container-1 div, then adding class card-container-1 to the \<dl> element and removing the \<span> elements, but be sure to update the css file as appropriate (moving the \<span> styling to \<dt> elements)

index.html
```html
<div class="card-container">
    <div class="card-container-1" id="search-result">
        <dl>
            <dt><span>Type</span></dt>
            <dd>Copy</dd>
            <dt><span>Length</span></dt>
            <dd>Copy.</dd>
            <dt><span>Diet</span></dt>
            <dd>Copy.</dd>
            <dt><span>Lived</span></dt>
            <dd>Copy.</dd>
            <dt><span>Species</span></dt>
            <dd>Copy.</dd>
            <dt><span>About</span></dt>
            <dd>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
                     tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, 
                     quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </dd>
        </dl>
    <div class="card-container-2"><img src="https://dummyimage.com/200x200/000/fff"></div>
</div>
```
styles.css
```css
.card-container {  
  border: 5px solid #777;
  border-radius: .5em;
  padding: 10px;
  display: inline-flex;
  padding: 20px;
  font: 1em Helvetica Neue, Helvetica, Arial, sans-serif;
}
.card-container-1 {
  width: 300px;
  min-height: 300px;
  padding-top: 10px;
  padding-bottom: 10px;
  padding-left: 10px;
  padding-right: 10px;
  background-color: #fff;
  border: 2px solid #fff;
}
.card-container-2 {
  width: 300px;
  min-height: 300px;
  padding: 10px;
  background-color: #fff;
  border: 2px solid #fff;
  display: flex;
  align-items: center;
  justify-content: center;
}
dl {
  display: grid;
  grid-template-columns: max-content 200px;
}
dt {
  grid-column-start: 1;
  padding-bottom: 20px;
  margin-right: -30px;
}
dd {
  grid-column-start: 2;
}
span {
  background-color: #777;
  border-radius: 4px;
  padding-left: 10px;
  padding-right: 10px;
  padding-top: 2px;
  padding-bottom: 2px;
}
```
